### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by aris0601** [spencereir/CirnoBot#1]
How do I install the bot onto my discord server?

**Comment by spencereir** [comment]
I won't assume anything about your setup, so here's a full description:

First install Go [here](http://golang.org). When that's done, make sure it's been added to your system PATH. You should be able to open up a command prompt and run `go version` successfully.  Run the following commands:

```
go get github.com/bwmarrin/discordgo
go get github.com/otium/ytdl
```

Either through the web interface or `git` program, download the code from this repository, and extract it somewhere. Navigate to this folder in command prompt and run `go build`. This will generate an executable. To run the executable, you'll need a Discord token. Go [here](https://discordapp.com/developers/applications/me) and register a new app. From within that app, you can get the app's token. Then you can launch the bot with the command `CirnoBot.exe "Bot <your token here>"` (On Windows, change as appropriate for other operating system). 

Finally you just need to add the bot to your server--from the app page, find your client ID. Go to the following URL:
[https://discordapp.com/oauth2/authorize?client_id=CLIENT_ID_GOES_HERE&scope=bot&permissions=0](https://discordapp.com/oauth2/authorize?client_id=CLIENT_ID_GOES_HERE&scope=bot&permissions=0), with your client ID replaced. You should be given the option to have the bot join.

**Comment by umairyousif239** [comment]
how can i add this to my server, can u explain it a bit more like what to do and?

**Comment by spencereir** [comment]
What about my above instructions do you need help with?

**Comment by umairyousif239** [comment]
That didnt work for me, it was showing that a file was missing

**Comment by spencereir** [comment]
Could you post a screenshot of your error so I can fix this?

**Comment by YouSelf239** [comment]
ok i have downloaded discord go and ytdl, what should i do now, and how?

**Comment by YouSelf239** [comment]
![screenshot 211](https://user-images.githubusercontent.com/37881515/39213443-0223bb12-482b-11e8-90fb-e277c21a918e.png)
this is what i am getting

**Comment by umairyousif239** [comment]
![screenshot 214](https://user-images.githubusercontent.com/37881515/39214920-98b64866-482f-11e8-9215-a238e2095215.png)
i am getting this error

**Comment by spencereir** [comment]
This appears to be an error with [cascadia](https://github.com/andybalholm/cascadia), not one with CirnoBot. Are you able to use that library successfully in other projects? Cirno does not rely on it, so it doesn't appear to be related to this project.

**Comment by umairyousif239** [comment]
well this is my first time doing this kind of stuff

**Comment by umairyousif239** [comment]
i am just stuck at that go build part

**Comment by spencereir** [comment]
As I mentioned in my previous reply, the code in this repository is unrelated to the error you are receiving. Try running `go get -u all` to update your packages, and see if you can use the cascadia package individually. You could also try running something like the following:

```
$ mkdir go-test; cd go-test; echo "package main\nimport fmt\nfunc main() { fmt.Printf("Test") }" > go-test/main.go
$ cd go-test
$ go build
```
to see if the error is with your Go. If this is still broken, I would recommend reaching out with your error at the cascadia project for more help.

**Comment by umairyousif239** [comment]
btw why dont u make a video guiding how to do this method

**Comment by umairyousif239** [comment]
i mean it will be easy for u to how to do it
